site: Dave Van Veen
author: Dave Van Veen

url: https://davevanveen.com # https://davevanveen.github.io
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  #posts:
  #  output: true
  #  permalink: /research/:slug
  #projects:
  #  output: true
  #  # permalink: /project/:slug
  #  permalink: /:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

paginate: 6
paginate_path: "/blog/page:num/"
# paginate_path: "/blog2/page:num/"

# seo tags
social:
  name: Dave Van Veen
  links:
  - https://www.linkedin.com/in/davevanveen/
  - https://www.strava.com/athletes/davevanveen
  - https://www.instagram.com/dave.vv/
  - https://github.com/davevanveen
  - https://scholar.google.com/citations?user=lP73UFAAAAAJ&hl=en

google_site_verification:
